6 コンフィグファイルの文法を定める
NaoyaFukuma/webserv pull request #11
Opened 2023-05-09 03:10 UTC by NaoyaFukuma

ANTLR4(.g4)を用いて、
＜参考URL＞
https://deadcode.rip/programming/antlr/g4.html
https://github.com/antlr/antlr4/blob/master/doc/lexer-rules.md

コンフィグファイルの文法規則をまとめました。

2023-05-09 04:12 UTC, tomofuji-dev requested changes
ありがとうございます、確認しました！

2023-05-09 04:12 UTC, tomofuji-dev commented on docs/conf.g4
> +config: server (server)+;
server+

2023-05-09 04:12 UTC, tomofuji-dev commented on docs/conf.md
> +- 概要: 仮想サーバーが待ち受けるドメイン名またはIPアドレスとポートを指定します。
注）複数指定された場合、エラー検出できず、最後に現れた項目の値が採用されます。

2023-05-09 04:12 UTC, tomofuji-dev commented on docs/conf.md
> +- 概要: サーバーに関連付けられたドメイン名またはIPアドレスを指定します。
注）複数指定された場合、エラー検出できず、最後に現れた項目の値が採用されます。

2023-05-09 04:12 UTC, tomofuji-dev commented on docs/conf.md
> +- 概要: パスのマッチング方法を指定します。`prefix`は接頭辞マッチング、`suffix`は接尾辞マッチングです。
注）複数指定された場合、エラー検出できず、最後に現れた項目の値が採用されます。

2023-05-09 04:12 UTC, tomofuji-dev commented on docs/conf.g4
> +	'location' PATH '{' directive_in_location* '}';
locationの中でrootがない場合はuriの検索をどのように行うのか、nginxの処理が気になります

2023-05-09 04:12 UTC, tomofuji-dev commented on docs/conf.g4
> +	| return_directive;
error_page, cgi_path directiveが必要だと思います

2023-05-09 04:12 UTC, tomofuji-dev commented on docs/conf.g4
> +	'allow_method' METHOD (METHOD)* END_DIRECTIVE;
METHOD+

2023-05-09 04:12 UTC, tomofuji-dev commented on docs/conf.g4
> +	'client_max_body_size' NUMBER END_DIRECTIVE;
1B, 1K, 1M, 1Gのような表記も対応できるようにしたいです

2023-05-09 04:12 UTC, tomofuji-dev commented on docs/conf.g4
> +	'location' PATH '{' directive_in_location* '}';
rootは必須にしましょう

2023-05-09 04:12 UTC, tomofuji-dev commented on docs/conf.g4
> +	'index' PATH (PATH)* END_DIRECTIVE;
PATH+

2023-05-09 04:12 UTC, tomofuji-dev commented on docs/conf.md
required:falseの時のデフォルト値を追記して欲しいです。

2023-05-09 04:12 UTC, tomofuji-dev commented on docs/conf.g4
> +NEWLINE: '\n' -> skip;
実装の段階で、newline+whitespaceをスキップする関数とwhitespaceのみをスキップする関数を区別する必要があります

2023-05-09 04:12 UTC, tomofuji-dev commented on docs/conf.g4
> +	| return_directive;
cgi_pathディレクティブはis_cgi: onだったら必須

2023-05-09 04:15 UTC, NaoyaFukuma commented on docs/conf.g4
> +config: server (server)+;
Done　Done　ダーン　だん

2023-05-09 04:16 UTC, NaoyaFukuma commented on docs/conf.md
> +- 概要: 仮想サーバーが待ち受けるドメイン名またはIPアドレスとポートを指定します。
だん

2023-05-09 04:17 UTC, NaoyaFukuma commented on docs/conf.md
> +- 概要: サーバーに関連付けられたドメイン名またはIPアドレスを指定します。
だん

2023-05-09 07:20 UTC, tomofuji-dev reviewed
ありがとうございます、いくつか聞きたいことがあったのでメモしました

2023-05-09 07:20 UTC, tomofuji-dev commented on docs/conf.g4
> +server: server_directive+;
修正前の、下記の方が正しいような気がします
server: 'server' '{' server_directive+ '}';

2023-05-09 07:20 UTC, tomofuji-dev commented on docs/conf.g4
> +	| timeout_directive
echoサーバーを実装してて、timeoutはepoll_waitのものと、event発火からの経過時間のものと2つあるのですが、configで設定するのは後者の方ですかね？

2023-05-09 07:20 UTC, tomofuji-dev commented on docs/conf.g4
> +	'index' PATH END_DIRECTIVE;
nginxだとindexは複数もokだと思いますが、ややこしそうですかね

2023-05-09 07:20 UTC, tomofuji-dev commented on docs/conf.g4
>  return_directive: 'return' URL;
nginxだと、下記の両方を許容しますが、indexと合わせてお聞きしたいです
return 404;
return 404 /not_found.html;

2023-05-10 02:18 UTC, NaoyaFukuma commented on docs/conf.g4
> +	| timeout_directive
後者の認識です！

2023-05-10 02:19 UTC, NaoyaFukuma commented on docs/conf.g4
> +server: server_directive+;
戻します！

2023-05-10 02:55 UTC, NaoyaFukuma commented on docs/conf.g4
> +	'index' PATH END_DIRECTIVE;
複数指定の機能は、現状、必要性が生じていないので、一旦制限して実装を用意にすることを選択したいと思います。

2023-05-10 03:15 UTC, NaoyaFukuma commented on docs/conf.g4
>  return_directive: 'return' URL;
Nginxが許容する構文は以下の３パターン。これに対応できるように修正。
return code [text];
return code URL;
return URL;

2023-05-10 05:02 UTC, tomofuji-dev commented on .vscode/settings.json
mergeする前に消したいです

2023-05-10 05:06 UTC, tomofuji-dev approved these changes
OKです、ありがとうございます！

2023-05-10 14:04 UTC, Chanmachan approved these changes
コードレビューさせてもらいました！

2023-05-10 14:04 UTC, merged