4 テスターとcmake行けるんじゃないかと思ってしまったんです
NaoyaFukuma/webserv pull request #15
Opened 2023-05-09 14:08 UTC by Chanmachan

rootのMakefileでtestのルールを実行してテストが走るようにした。
dockerを起動してシェルスクリプトを走らせてます。
現在実行されるシェルスクリプト(server_test.sh)は適当なコマンドを羅列してるだけですが、ファイルの実行やらなんやらを追加していけば使えるはずです。
実行したいテスト(シェルスクリプト)を変更したい場合は、docker-compose.yml内のENTRYPOINTを変更してください。
あとは色々いじってもろて

2023-05-09 14:35 UTC, tomofuji-dev reviewed
階層構造として、以下はserverフォルダにまとめていいと思います
- server_test.sh
- Dockerfile
- docker-entrypoint.sh

2023-05-09 14:36 UTC, tomofuji-dev commented on tests/docker/Dockerfile
> +RUN			mkdir -p /root/workdir
削除

2023-05-09 14:37 UTC, tomofuji-dev commented on tests/docker/Dockerfile
> +COPY ./tests/docker/docker-entrypoint.sh /app/docker-entrypoint.sh
これは不要なはず
ENTRYPOINT ["/app/tests/server/docker-entrypoint.sh"]とすれば多分動く

2023-05-10 02:17 UTC, NaoyaFukuma approved these changes
Dockerわからない！まかせた！

2023-05-10 05:10 UTC, tomofuji-dev requested changes
以下3つはServerフォルダにまとめたいです
- server_test.sh
- Dockerfile
- docker-entrypoint.sh

2023-05-11 14:02 UTC, tomofuji-dev commented
#23 にてmerge

2023-05-11 14:02 UTC, closed without merging