ドラフト
NaoyaFukuma/webserv pull request #20
Opened 2023-05-10 05:33 UTC by NaoyaFukuma

2023-05-10 05:34 UTC, tomofuji-dev approved these changes
確認しました、抜けもれないと思います

2023-05-10 08:56 UTC, tomofuji-dev approved these changes
OKです！

2023-05-12 04:38 UTC, Chanmachan approved these changes
問題なさそうです。テストしながら何かあればリファクタしていく形だと思います。

2023-05-12 04:38 UTC, Chanmachan commented on docs/conf.md
> +以下のパターンを許容します。
以下が抜けてたりします？

2023-05-12 04:38 UTC, Chanmachan commented on srcs/config/ConfigParser.cpp
> +    int column = 1;
1の代入はいらなそう

2023-05-13 02:12 UTC, tomofuji-dev requested changes
ありがとうございます、ConfigParser.cpp, Config.cpp, conf.mdを中心に確認しました！
いくつかコメントしましたので、よろしくお願いします。

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +                            "Expected 'server'");
関数にまとめていいと思います

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +    if (token == "match") {
swtich caseに直したいです

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +}
\nを他の空白文字と同一視しているので、以下のようなケースも許容します。
webservでは許容することにしてもいいですが、nginxだとparseerrorになるので検討したいです。
```
listen


 hoge:8000
```
SkipSpaceの引数に改行あるなしを指定できるようにして、ディレクティブを読み込んだ後のSkipSpace()を改行なしで実行するとか？

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +    host_str = "0.0.0.0";
めっちゃ細かいですが、portと同じくhostもvoid ConfigParser::ParseServer(Config &config)の最初の部分で初期化してもいいかも

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +  if (!ws_strtoi<int>(&dest_timeout, timeout_str)) {
以前見た時、timeoutの単位として's'をつけていたと思うのですが、単位をつけないよう変更しました？

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +  if (!ws_strtoi<int>(&dest_timeout, timeout_str)) {
's'つけなくてもいいかなと思ってた部分なので、上記仕様ならこのままで大丈夫だと思います

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +                            "Expected 'server'");
assert内のthrowでもこれを使っていいかなと思いました

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +  for (std::string::const_iterator it = server_name.begin();
servernameはip/domain名の両方を許容しますが、ipアドレスのチェックはIsValidLabel（）をループで実行することに含まれているという認識でいいですか？

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +    }
自分で書いた部分ですが、switch caseに書き直したいです（コンパイラの最適化）

2023-05-13 02:12 UTC, tomofuji-dev commented on docs/conf.md
>  注）複数指定された場合、エラー検出できず、最後に現れた項目の値が採用されます。
細かい日本語ですが、「エラー検出できず」ではなく「エラーとして検出せず」がいいです。
仕様でしっかり定義して、あえてそうしてないだけなんだからね！

2023-05-13 02:12 UTC, tomofuji-dev commented on docs/conf.md
>  注）複数指定された場合、エラー検出できず、最後に現れた項目の値が採用されます。
他も同様の箇所があるので省略

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +  }
ここもswitch caseに直したいです

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +bool AssertPath(const std::string &path) {
自分用メモ：config parseの部分では使用している文字種のチェックだけ　accessできないパスが指定されていたら、対応するerrorレスポンスを返す

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +  }
try catchでstd::overflow_errorを検知して、parserExceptionとして再throwしたいです

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +bool AssertPath(const std::string &path) {
boolを返しているので、IsValidPathでもいいかも

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +void ConfigParser::AssertIndex(const std::string &index) {
// indexディレクティブは、rootディレクティブが設定されている場合のみ有効
-> rootは必須項目だと思います

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +
root + indexみたいな形で使うと思うので、最後の文字が'/'であることをことを保証しておくといいと思いました
indexが/で始まる場合でも、そうでない場合でも、root + indexでpathが通るようになると思います

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +
追記：parserの時点でそれを行うのではなく、実行時にroot + '/' + indexの形にするのがいい気がしてきました

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +}
現状だと、以下も許容します
```
listen hoge:8000
;
```

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +  }
それか、overflowのチェック関数をis_mul_overflow()とboolを返すように書き返すのでもいいと思います。

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +      if (tmp_str[0] == '\'') {
最後が'であるチェックもした方がいいと思います

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +        location.return_.return_text_ = tmp_str.substr(1, tmp_str.size() - 2);
tmp_str.size() < 2の時オーバーフローします

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +      if (tmp_str[0] == '\'') {
最後が'でなければ、URLとしてみなす

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +        location.return_.return_url_ = tmp_str;
ここでurlのassertはしなくていいですか？

2023-05-13 02:12 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +    location.return_.return_url_ = tmp_str;
同上、urlのassertについて

2023-05-13 02:12 UTC, tomofuji-dev commented on docs/config/valid_case/full_test.conf
単体テストの作成にあたって、invalid, validともにtestケースを作りたいです
ここら辺はちゃんまさんの作業と合わせて、3人でやりましょう

2023-05-13 09:01 UTC, NaoyaFukuma commented on docs/conf.md
>  注）複数指定された場合、エラー検出できず、最後に現れた項目の値が採用されます。
注）複数指定された場合、エラーとして扱わず、最後に現れた項目の値を採用します。

と修正。エラーとして扱わないことと、最後を採用することを端的な肯定文で記すことで、この挙動が意図したものであることがわかるようにした。
（端的な肯定文でって、日本語あってるのか？）

2023-05-13 09:08 UTC, NaoyaFukuma commented on srcs/config/ConfigParser.cpp
> +  if (!ws_strtoi<int>(&dest_timeout, timeout_str)) {
's'無しに変更しました。Nginxの仕様を調べているうちに、's' はオプション扱いで、省略も許容することに気づき、冗長さを無くし、複数の設定方法があることによる混乱を防ぐために、's' 無ししか許容しない仕様にしました。

2023-05-13 09:33 UTC, NaoyaFukuma commented on srcs/config/ConfigParser.cpp
> +                            "Expected 'server'");
こんな感じにまとめてみました

```c++
// parse error時に、例外をスローする
void ConfigParser::ThrowParseError(const char *msg, bool err_msg_only = true) {
  if (err_msg_only) {
    throw ParserException(ERR_MSG, msg);
  } else {
    int row;
    int col;
    std::string line;
    this->GetErrorPoint(row, col, line);
    throw ParserException(ERR_MSG_ROW_COL_LINE, row, col, line.c_str(), msg);
  }
}

// parser
void ConfigParser::Parse(Config &config) {
  while (!this->IsEof()) {
    this->SkipSpaces();
    if (this->GetWord() != "server") {
      this->ThrowParseError("Expected 'server'", false);
    }
    this->ParseServer(config);
    this->SkipSpaces();
  }
  AssertConfig(config);
}
```

2023-05-13 12:42 UTC, NaoyaFukuma commented on srcs/config/ConfigParser.cpp
> +    if (token == "match") {
string型を使って書くことはできますか？

2023-05-13 13:00 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +    if (token == "match") {
確かに、stringで使えないですね;;

2023-05-13 13:42 UTC, NaoyaFukuma commented on srcs/config/ConfigParser.cpp
> +}
SkipSpaces()を修正し、スキップ対象に改行を含めるかを設定できるように修正。
そのうえで、改行をスキップしたくない箇所、
ディレクティブとパラメータの間、パラメータとセミコロンの間でのSkipSpaces()呼び出しを修正

2023-05-13 14:10 UTC, NaoyaFukuma commented on srcs/config/ConfigParser.cpp
> +    host_str = "0.0.0.0";
Vserver, Locationこれらの構造体のコンストラクタを設けました！

2023-05-13 14:19 UTC, NaoyaFukuma commented on srcs/config/ConfigParser.cpp
> +  for (std::string::const_iterator it = server_name.begin();
たしかに！
IPかドメイン名かの判定を入れて、どちらもValidationします！

2023-05-13 14:24 UTC, NaoyaFukuma commented on srcs/config/ConfigParser.cpp
> +  for (std::string::const_iterator it = server_name.begin();
IPアドレスのフォーマットに適合するならIPアドレスとして扱い、
そうでないなら、ドメイン名として扱うように修正しました！

2023-05-13 14:36 UTC, NaoyaFukuma commented on srcs/config/ConfigParser.cpp
> +bool AssertPath(const std::string &path) {
IsValidPathに修正

2023-05-14 04:25 UTC, NaoyaFukuma commented on srcs/config/ConfigParser.cpp
> +  }
try catchで囲みました！

```c++
  try {
    switch (unit) {
    case 'B':
      break;
    case 'K':
      dest_size = mul_assert_overflow<uint64_t>(dest_size, 1024);
      break;
    case 'M':
      dest_size = mul_assert_overflow<uint64_t>(dest_size, 1024 * 1024);
      break;
    case 'G':
      dest_size = mul_assert_overflow<uint64_t>(dest_size, 1024 * 1024 * 1024);
      break;
    default:
      char unit_str[4] = {'\'', unit, '\'', '\0'};
      throw ParserException(ERR_MSG, (std::string(unit_str) +
                                      " is Invalid client_max_body_size unit")
                                         .c_str());
    }
  } catch (const std::overflow_error &e) {
      throw ParserException(ERR_MSG, (std::string(size_str) +
                                      " is Invalid 'uint64_t' overflow client_max_body_size")
                                         .c_str());
    
  }
```

2023-05-14 04:30 UTC, NaoyaFukuma commented on srcs/config/ConfigParser.cpp
> +void ConfigParser::AssertIndex(const std::string &index) {
コメントを削除

2023-05-14 04:34 UTC, NaoyaFukuma commented on srcs/config/ConfigParser.cpp
> +      if (tmp_str[0] == '\'') {
先頭のみしかチェックしていなかったものを、末尾のチェックも追加対応。

2023-05-14 04:38 UTC, NaoyaFukuma commented on srcs/config/ConfigParser.cpp
> +        location.return_.return_text_ = tmp_str.substr(1, tmp_str.size() - 2);
当該処理の直前のif文を書き直したことで、２文字以上が保証されるようになったため、修正不要と判断。

2023-05-14 08:07 UTC, Chanmachan commented
status_code_って指定がない場合って初期化とかって必要ないですか？

2023-05-14 12:57 UTC, NaoyaFukuma commented
@Chanmachan 
> status_code_って指定がない場合って初期化とかって必要ないですか？

return ディレクトリが.confに存在しない場合、
enum return_type が、EMPTYになっているので、
status_code_がHTTPリクエスト処理時に読み込まれることはない。という前提から、
return ディレクトリが存在しない場合は、status_code_が未初期化かつ値の代入がされない状態を許容しています。

266行目の以下の部分のことですか？

  } else { // status codeがない場合はURLとみなす
    location.return_.status_code_ = 302; // defaultはリダレクト
    location.return_.return_type_ = RETURN_URL;
    location.return_.return_url_ = tmp_str;
  }

2023-05-14 13:00 UTC, NaoyaFukuma commented on srcs/config/ConfigParser.cpp
> +        location.return_.return_url_ = tmp_str;
以下のassert関数でURLのチェックを行えるようにしました！
void ConfigParser::AssertReturn()
546行目

2023-05-14 13:00 UTC, NaoyaFukuma commented on srcs/config/ConfigParser.cpp
> +    location.return_.return_url_ = tmp_str;
同上

2023-05-15 01:09 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +        location.return_.return_text_ = tmp_str.substr(1, tmp_str.size() - 2);
GetWord()の結果が"'"だった場合、if文の条件を突破してsize() - 2でオーバーフローしませんか？

2023-05-15 01:11 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +      if (tmp_str[0] == '\'') {
"'"がこの条件を突破するので、size() >= 2 をチェックした方が良さそうです

2023-05-15 01:23 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +  this->SkipSpaces();
true

2023-05-15 01:30 UTC, tomofuji-dev commented on srcs/config/ConfigParser.cpp
> +    host_str = "0.0.0.0";
INADDR_ANY

2023-05-15 01:32 UTC, tomofuji-dev approved these changes
2点だけ追加でコメントしました。mergeお願いします！

2023-05-15 02:04 UTC, merged