24 unit test
NaoyaFukuma/webserv pull request #31
Opened 2023-05-13 19:28 UTC by Chanmachan

書いててわかったんですけど、テストコードを一般化する方法が全く思いつかずベタ打ちテストになってますがそれなりに動いてくれると思います。
CMakeをリポジトリに追加しちゃったので許してください。
ymlファイルも追加しましたが、GitHubActions上で動くか試していないのでマージ終わったらpushしてみて欲しいです。
全てにおいて美しさがかけてるので構造含め後に変更したいと思ってます。

2023-05-15 01:53 UTC, tomofuji-dev commented
以下についてすり合わせしたいです。
・CMakeを使うかどうか
・CMakeをunit testで使うのであれば、webservのビルドもCMakeに統一したい(echo_testも)
・手元のCLIでCMakeを起動する方法を聞きたい

2023-05-15 03:44 UTC, tomofuji-dev requested changes
・CMakeLists.txtをsrcs->unit-testに分離したい
・Makefileの中にunit-testのターゲットを追加して欲しい

2023-05-17 03:59 UTC, NaoyaFukuma approved these changes

2023-05-17 03:59 UTC, NaoyaFukuma commented on docs/config/config.conf
/docs/config/ ディレクトリに配置する.confファイルと、
/unit-test/config/ ディレクトリに配置する.confファイルについて、
それぞれの役割を切り分けたいと思います。

/docs/config/ 配下は、正常シナリオを想定し、実装した各種HTTPサーバーの機能が活用できるような設定を持った.confファイルを一つだけ配置する。

/unit-test/config/ 配下に、エラーシナリオやエッジケースといったテスト用の.confを配置する。

別issueへ切り出しておきます！

2023-05-17 03:59 UTC, tomofuji-dev approved these changes
ありがとうございます、OKです

2023-05-17 04:00 UTC, merged