77 request parser残りタスク
NaoyaFukuma/webserv pull request #89
Opened 2023-06-05 08:00 UTC by Chanmachan

ヘッダーをまとめたのと、アサートの追加が作業内容だったと思います。
確認お願いします。

> ウェブサーバー（例えばnginx）はセキュリティ上の理由から、ドキュメントルート（ここでは/var/www/）より上のディレクトリにアクセスするのを制限することがあります。

今はrootに入った時点で弾く処理になってます。

2023-06-05 12:59 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
std::strtol() c++ 11

2023-06-05 13:04 UTC, NaoyaFukuma requested changes
std::strtol()が残ってしまっていました！

2023-06-06 11:59 UTC, tomofuji-dev commented on srcs/http/Request.cpp
> +    uint64_t client_max_body_size = socket->GetConfVec()[0].locations_[0].client_max_body_size_;
client_max_body_sizeはresolve_pathの後にわかるはずです。
常に最初のvserverの最初のlocationブロックのclient_max_body_sizeを見に行ってます。

2023-06-06 12:00 UTC, tomofuji-dev commented on srcs/http/Request.cpp
> +template<typename T>
long以外の型で使わないのなら、templateを使わなくていい気もします

2023-06-06 12:05 UTC, tomofuji-dev commented on srcs/http/Request.cpp
>    }
..の数だけではチェックできないと思います。
多分余計に弾いてしまう(/root/../rootとか)

2023-06-06 12:08 UTC, tomofuji-dev commented on srcs/http/Request.cpp
> +    if (!AssertSize(total_body_size_, static_cast<long>(client_max_body_size))) {
AssertSizeはRequest classの関数なので、引数いらないと思います

2023-06-06 12:10 UTC, tomofuji-dev commented on srcs/http/Request.cpp
> +    default:break;
linterについて確認させてください

2023-06-06 12:16 UTC, tomofuji-dev commented on srcs/http/Request.cpp
>    }
ws_splitが"../"を入力にとると、["..", ""]を返すので、空文字列を考慮する必要がありそう

2023-06-06 12:21 UTC, tomofuji-dev commented on srcs/http/Request.cpp
> +    if (!AssertSize(total_body_size_, static_cast<long>(client_max_body_size))) {
static_castを排除したいので、locationのclient_max_body_sizeと、total_body_sizeをsize_tに揃えたいです

2023-06-06 13:52 UTC, Chanmachan commented on srcs/http/Request.cpp
> +    default:break;
すんません、設定直したのでこれで大丈夫だと思います

2023-06-06 14:05 UTC, Chanmachan commented on srcs/http/Request.cpp
>    }
> nginxのようなWebサーバを自身で実装する場合、親ディレクトリへの遡行（つまり、"../"を含むパスへのアクセス）をデフォルトでエラーにするのはセキュリティ上一般的な設計です。
> 
> これは、Webサーバの外部から任意のディレクトリやファイルへのアクセスを制限するための重要な措置です。特に公開サーバでは、この種のアクセス制限がないと、攻撃者が重要なファイルやデータにアクセスしたり、サーバを不正に操作する可能性があります。
>
> したがって、自分でWebサーバを実装する場合には、親ディレクトリへの遡行をデフォルトでエラーにすることを強く推奨します。そして、特定のディレクトリやファイルへのアクセスを許可する必要がある場合には、それらのパスを明示的に設定することが一般的です。
>
> また、Webサーバの設定だけでなく、アプリケーションレベルでもこの種のパスをチェック・フィルタすることが一般的なセキュリティ対策です。これらの対策は、セキュアなWebサーバやアプリケーションを構築するために非常に重要です。
>
この話かなって思ってて、自分の実装だとふじわらさんが言ってるやつはcounterが一瞬マイナスになるのでエラーになる実装にしたつもりでした

2023-06-08 02:37 UTC, Chanmachan commented on srcs/http/Request.cpp
> +template<typename T>
修正

2023-06-08 02:38 UTC, Chanmachan commented on srcs/http/Request.cpp
> +    if (!AssertSize(total_body_size_, static_cast<long>(client_max_body_size))) {
修正

2023-06-08 02:39 UTC, Chanmachan commented on srcs/http/Request.cpp
> +    uint64_t client_max_body_size = socket->GetConfVec()[0].locations_[0].client_max_body_size_;
AssertSize関数ないでGetContextから正しい変数を確認するように変更

2023-06-10 07:11 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
>      message_ = rhs.message_;
コンテキストの代入は必要です！
たぶん間違って消したのかも
他にも必要な処理が無いかも要確認ですね

2023-06-10 07:16 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
> +  if (socket) {
ConnSocket *socket がNULLのときって存在しないんじゃないでしょうか？
ポインターが指すインスタンスが消滅していることを想定している？そのケースはNULLチェックではハンドリングできないけど、ここの意図がわからなかったです！

2023-06-10 07:52 UTC, Chanmachan commented on srcs/http/Request.cpp
>      message_ = rhs.message_;
修正

2023-06-10 13:16 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
>      } else {
HTTP 505 HTTP Version Not Supported
か、HTTP/1.1で処理を進める方法もあります。

2023-06-10 13:20 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
> +  if (!SetBodyType()) {
バッファーがemptyとは限らないのでは？

2023-06-10 13:29 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
> +  if (!SetBodyType()) {
コンテントタイプがマイナスでこのif文に入り、バッファがempty()だったら、不正なリクエストなのにコンプリートになりませんか？

2023-06-10 13:31 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
>        // error
content-lengthに０を許容する理由はありますか？？

2023-06-10 13:35 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
>      message_ = rhs.message_;
修正済みですか？

2023-06-10 13:37 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
> +  if (!SetBodyType()) {
CHUNK受信の２度目以降に対応できていないのでは？？

2023-06-10 13:42 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
> +  // size_strを16進数に変換
std::string　size_str(16進数)を、long chunk_status_に変換
とかでしょうか？
size_str自体は元々16進数表記では？？

2023-06-10 13:52 UTC, Chanmachan commented on srcs/http/Request.cpp
>      message_ = rhs.message_;
リモートにプッシュしてませんでした🙇

2023-06-10 13:54 UTC, Chanmachan commented on srcs/http/Request.cpp
> +  if (socket) {
socketを渡さない状態でもテストできるようにしていたのでこの書き方になっていました。
なのでnullが渡ってくる時は基本存在しないです。

2023-06-10 13:57 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
>      std::string::size_type pos = chunk.rfind("\r\n");
rfind()は末尾を保証しませんが大丈夫ですか？

2023-06-10 13:58 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
> +      parse_status_ = BODY;
ERRORではなくなった？？
BODYにするなら、元々BODYではなかった？？

2023-06-10 14:00 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
>      if (pos == chunk.size() - 2) {
この条件式が真にならなかったときの処理は不要ですか？

2023-06-10 14:05 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
>      if (pos == chunk.size() - 2) {
buf = buf.substr(0, pos);
の第二引数のiteratorが別のインスタンスのものですが、問題ないですか？

2023-06-10 14:05 UTC, Chanmachan commented on srcs/http/Request.cpp
>      } else {
505,parse_statusをエラーに

2023-06-10 14:10 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
>    // headerにContent-LengthかTransfer-Encodingがあるかを調べる
EPOLLINイベントがまたがるchunk送信に、ここで、
is_chunked_がtrueなら、trueをreturnする処理で対応できそうです

2023-06-10 14:13 UTC, Chanmachan commented on srcs/http/Request.cpp
>      if (pos == chunk.size() - 2) {
else {
      SetRequestStatus(400);
      parse_status_ = ERROR;
      return;
}

2023-06-10 14:15 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
>        return false;
std::vector<std::string> valuesがempty()でないことが保証されていないのでは？

2023-06-10 14:19 UTC, Chanmachan commented on srcs/http/Request.cpp
> +      parse_status_ = BODY;
BODY -> ERROR

2023-06-10 14:21 UTC, Chanmachan commented on srcs/http/Request.cpp
>    // headerにContent-LengthかTransfer-Encodingがあるかを調べる
if (is_chunked_) {
    return true;
  }

2023-06-10 14:38 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
> +    host = message_.header["Host"][0];
ここ消さないほうがよいのでは？？

2023-06-11 12:49 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
>  void Request::ParseLine(const std::string &line) {
ここでエラー400で上書きされてしまうのではないですか？

2023-06-11 12:55 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
>  void Request::ParseLine(const std::string &line) {
９３行目が実行されるケースはありますか？
ParseLineを呼び出す側のwhile()で、ERRORはwhile()ループ　の継続条件から除外されているので、
93行目が実行されるケースはないのでは？
そうすると、エラーに基づくhttp statusが設定されずに次のステップに移行することになるのではないでしょうか？

2023-06-11 12:57 UTC, NaoyaFukuma commented on srcs/http/Request.cpp
>      return false;
ここで不正なリクエストを検知した段階でerror statusをセットしたほうが良いのでは？
ほかも同じくリクエストに対するステータスが決まった段階でstatusを都度設定し、ステータスを使い分ける必要があるのでは？

2023-06-12 13:37 UTC, merged